## Numpy matrix with 2d but just one column

In [1]:
import numpy as np

layer_0 = np.zeros((1,10))
layer_0


array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [2]:
layer_0[0]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [14]:
layer_0[0][1]

weights_0_1 = np.zeros((5,10))
weights_0_1[0][0] = 3
weights_0_1[3][4] = 2
weights_0_1[4][9] = 4

layer_0[0] *= 0 #reset
layer_0[0] += weights_0_1[3]

print(weights_0_1)
print('*********************')
print(layer_0)


[[ 3.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  2.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  4.]]
*********************
[[ 0.  0.  0.  0.  2.  0.  0.  0.  0.  0.]]
